name = "runcrew-backend"
main = "src/index.js"
compatibility_date = "2024-11-20"

[vars]
JWT_ISSUER = "runcrew.app"
JWT_AUDIENCE = "runcrew-users"

[[kv_namespaces]]
binding = "KV_APP"
id = "3668d012c4f34801a6a2936fa682abad"