name = "runcrew-backend"
main = "src/index.js"
compatibility_date = "2024-11-20"

[vars]
# JWT (식별자만 노출, 키 값은 secret로)
JWT_ISSUER   = "runcrew.app"
JWT_AUDIENCE = "runcrew-users"
AUTH_SECRET  = "3249a0d73ac68118509d6dabdade7cdad5c80f08e43c6be3cda06471ec495cbd"

# Supabase (서비스 키는 secret!)
SUPABASE_URL = "https://yxfkpddrakhnccpqttzl.supabase.co"

# GH Pages CORS 허용
CORS_ORIGINS = "https://popple1101.github.io,https://popple1101.github.io/runningcrew"

# ── 기본(production) 콜백 ──
KAKAO_REDIRECT_URI = "https://runcrew-backend.popple1101.workers.dev/auth/kakao/callback"
NAVER_REDIRECT_URI = "https://runcrew-backend.popple1101.workers.dev/auth/naver/callback"

# ── 로컬 전용 env (원하면 사용) ──
[env.dev.vars]
KAKAO_REDIRECT_URI = "http://localhost:8787/auth/kakao/callback"
NAVER_REDIRECT_URI = "http://localhost:8787/auth/naver/callback"
