name = "runcrew-backend"
main = "src/index.js"
compatibility_date = "2024-11-20"

[vars]
# === JWT / 세션 ===
JWT_ISSUER   = "runcrew.app"
JWT_AUDIENCE = "runcrew-users"
JWT_SECRET   = "change_this_to_a_long_random_string"
# (코드가 AUTH_SECRET를 쓴다면 임시 호환)
AUTH_SECRET  = "change_this_to_a_long_random_string"

# === Supabase ===
# 서비스 롤 키는 toml에 넣지 말고 secret로!
SUPABASE_URL = "https://yxfkpddrakhnccpqttzl.supabase.co"

# === Kakao OAuth ===
KAKAO_CLIENT_ID    = "13586043acea1473bd2a63898f8b9043"
# 콜백은 '백엔드'로 (서버사이드 토큰교환)
KAKAO_REDIRECT_URI = "http://localhost:8787/auth/kakao/callback"
# client secret은 secret로!
# KAKAO_CLIENT_SECRET 는 toml에 두지 않음
